baseURL = "/" # is used as base for absURL and is overridden by HUGO_BASEURL env var
languageCode = "en"
title = "Learn it my way"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
pygmentsCodeFences = true
pygmentsUseClasses = true

[pagination]
  pagerSize = 6

[params]
  description = "David's learning experiences as a self-taught software developer"
  shareImage = "https://res.cloudinary.com/developerdavo/image/upload/f_auto,w_1200/v1590954325/learnitmyway/header.png"
  author = "David"
  about = "Thanks for visiting Learn it my way! I created this website so I could share my learning experiences as a self-taught software developer."
  github = "https://github.com/learnitmyway"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false